# CSC4792 Data Mining and Warehousing
## Group 26 — Mpongwe Town Council Dataset
This notebook documents the extraction, cleaning, preprocessing, validation and export of data collected from official Mpongwe Town Council sources.

In [37]:
import pandas as pd

In [38]:
file_path = "../data/processed/db-unza26-csc4792-mpongwe_cdf_projects.csv"

df = pd.read_csv(file_path, sep="|")

df.head()

,project_id,sector,ward,project_name,approval_status,reason_not_approved,year,source_document,source_url
0,CDF2025-001,Education,Kasamba,Construction of a 1X4 CRB at Kasamba Secondary...,Not Approved,Inadequate funding,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,http://www.mpongwecouncil.gov.zm/wp-content/up...
1,CDF2025-002,Health,Kasamba,Construction of 1 staff house and completion o...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,http://www.mpongwecouncil.gov.zm/wp-content/up...
2,CDF2025-003,Education,Kasamba,Construction of 1 staff house; purchase of 80 ...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,http://www.mpongwecouncil.gov.zm/wp-content/up...
3,CDF2025-004,Education,Kasamba,Construction of a Community School at Fikola a...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,http://www.mpongwecouncil.gov.zm/wp-content/up...
4,CDF2025-005,Education,Kasamba,Construction of 1 staff house and purchase of ...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,http://www.mpongwecouncil.gov.zm/wp-content/up...

In [39]:
df.shape

(5, 9)

## Initial Data Inspection

The dataset is inspected to verify its structure, data types, missing values and possible duplicate records before further processing.

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   project_id           5 non-null      str
 1   sector               5 non-null      str
 2   ward                 5 non-null      str
 3   project_name         5 non-null      str
 4   approval_status      5 non-null      str
 5   reason_not_approved  5 non-null      str
 6   year                 5 non-null      int64
 7   source_document      5 non-null      str
 8   source_url           5 non-null      str
dtypes: int64(1), str(8)
memory usage: 492.0 bytes

In [41]:
df.isnull().sum()

project_id             0
sector                 0
ward                   0
project_name           0
approval_status        0
reason_not_approved    0
year                   0
source_document        0
source_url             0
dtype: int64

In [42]:
df.duplicated().sum()

np.int64(0)

## Source URL Completion

In [43]:
source_url = "http://www.mpongwecouncil.gov.zm/wp-content/uploads/2025/11/APPROVED-AND-UNAPPROVED-COMMUNITY-PROJECTS-2025.pdf"
df["source_url"] = df["source_url"].fillna(source_url)

In [44]:
df.isnull().sum()

project_id             0
sector                 0
ward                   0
project_name           0
approval_status        0
reason_not_approved    0
year                   0
source_document        0
source_url             0
dtype: int64

## Text Cleaning and Standardisation

In [45]:
text_columns = [
    "sector",
    "ward",
    "project_name",
    "approval_status",
    "reason_not_approved",
    "source_document"
]
for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

In [46]:
df["sector"] = df["sector"].str.title()
df["ward"] = df["ward"].str.title()
df["approval_status"] = df["approval_status"].str.title()

In [47]:
df["project_name"] = (
    df["project_name"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

df["reason_not_approved"] = (
    df["reason_not_approved"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [48]:
df[
    [
        "project_id",
        "sector",
        "ward",
        "project_name",
        "approval_status",
        "reason_not_approved"
    ]
]

,project_id,sector,ward,project_name,approval_status,reason_not_approved
0,CDF2025-001,Education,Kasamba,Construction of a 1X4 CRB at Kasamba Secondary...,Not Approved,Inadequate funding
1,CDF2025-002,Health,Kasamba,Construction of 1 staff house and completion o...,Not Approved,It was not the first priority
2,CDF2025-003,Education,Kasamba,Construction of 1 staff house; purchase of 80 ...,Not Approved,It was not the first priority
3,CDF2025-004,Education,Kasamba,Construction of a Community School at Fikola a...,Not Approved,It was not the first priority
4,CDF2025-005,Education,Kasamba,Construction of 1 staff house and purchase of ...,Not Approved,It was not the first priority

## Data Validation

The cleaned sample is validated for duplicate records, missing values, consistent categorical values, and expected data types before additional records are added.

In [49]:
df.duplicated().sum()
df.isnull().sum()
df["sector"].value_counts()
df["ward"].value_counts()
df["approval_status"].value_counts()

approval_status
Not Approved    5
Name: count, dtype: int64

In [50]:
df.duplicated().sum()

np.int64(0)

In [51]:
df["sector"].value_counts()

sector
Education    4
Health       1
Name: count, dtype: int64

In [52]:
df.dtypes

project_id               str
sector                   str
ward                     str
project_name             str
approval_status          str
reason_not_approved      str
year                   int64
source_document          str
source_url               str
dtype: object

Add this Markdown cell:
## Export Cleaned Sample

In [53]:
output_path = "../data/processed/db-unza26-csc4792-mpongwe_cdf_projects.csv"

In [54]:
df.to_csv(
    output_path,
    sep="|",
    index=False
)

In [55]:
check_df = pd.read_csv(output_path, sep="|")

check_df.head()

,project_id,sector,ward,project_name,approval_status,reason_not_approved,year,source_document,source_url
0,CDF2025-001,Education,Kasamba,Construction of a 1X4 CRB at Kasamba Secondary...,Not Approved,Inadequate funding,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,http://www.mpongwecouncil.gov.zm/wp-content/up...
1,CDF2025-002,Health,Kasamba,Construction of 1 staff house and completion o...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,http://www.mpongwecouncil.gov.zm/wp-content/up...
2,CDF2025-003,Education,Kasamba,Construction of 1 staff house; purchase of 80 ...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,http://www.mpongwecouncil.gov.zm/wp-content/up...
3,CDF2025-004,Education,Kasamba,Construction of a Community School at Fikola a...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,http://www.mpongwecouncil.gov.zm/wp-content/up...
4,CDF2025-005,Education,Kasamba,Construction of 1 staff house and purchase of ...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,http://www.mpongwecouncil.gov.zm/wp-content/up...

In [56]:
check_df.shape

(5, 9)

## PDF Extraction Test
The original 2025 Mpongwe CDF document is tested to determine whether its text can be extracted programmatically before processing the complete dataset.

In [57]:
%pip install pdfplumber

Requirement already satisfied: pdfplumber in c:\users\bautis chileshe\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.11.10)
Requirement already satisfied: pdfminer.six==20260107 in c:\users\bautis chileshe\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pdfplumber) (20260107)
Requirement already satisfied: Pillow>=12.2.0 in c:\users\bautis chileshe\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pdfplumber) (12.3.0)
Requirement already satisfied: pypdfium2>=5.9.0 in c:\users\bautis chileshe\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pdfplumber) (5.13.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\bautis chileshe\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pdfminer.six==20260107->pdfplumber) (3.4.3)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\bautis chileshe\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pdfminer.six==20260107->pdfplumber) (50.0.1)
Requirement already satisfied: cffi>=2.0.0 in c:\users\bautis chileshe\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.1.1)
Requirement already satisfied: pycparser in c:\users\bautis chileshe\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from cffi>=2.0.0->cryptography>=36.0.0->pdfminer.six==20260107->pdfplumber) (2.22)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.2.1
[notice] To update, run: C:\Users\Bautis Chileshe\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [58]:
import pdfplumber

In [59]:
pdf_path = "../data/raw/mpongwe_cdf_projects_2025.pdf"

In [60]:
with pdfplumber.open(pdf_path) as pdf:
    print("Number of pages:", len(pdf.pages))

Number of pages: 9

In [61]:
with pdfplumber.open(pdf_path) as pdf:
    first_page_text = pdf.pages[0].extract_text()

print(first_page_text)

MINISTRY OF LOCAL GOVERNMENT AND RURAL DEVELOPMENT - MPONGWE
TOWN COUNCIL
COMMUNITY PROJECTS
MPONGWE CONSTITUENCY 2025 APPROVED AND NOT APPROVED CDF PROJECTS
Project Name/ Sector Ward Approved Not Approved
No. Description
1 Construction of a Education Kasamba Inadequate Funding
1X4 CRB at
Kasamba
Secondary
School with
laborotory;purch
ase of 200
desks,one staff
house and solar
powered
borehole
2 Construction of 1 Health Kasamba It was not the first
staff house and priority
completion of 1
staff house at
Kasamba Rural
Health Center
3 Construction of 1 Education Kasamba It was not the first
staff house; priority
purchase of 80
desks and solar
powered
borehole at
Mikumbi
primary School
4 Construction of a Education Kasamba It was not the first
Community priority
School at Fikola
area.
5 Construction of 1 Education Kasamba It was not the first
staff house and priority
purchase of 80
desks at
Minkoyo
Primary School
6 Construction of a Health Kasamba It was not the first
health post at priority
Bwandaila in
Milonfi

In [62]:
with pdfplumber.open(pdf_path) as pdf:
    first_page = pdf.pages[0]
    tables = first_page.extract_tables()

print("Number of tables found:", len(tables))

Number of tables found: 6

In [63]:
if tables:
    for row in tables[0][:10]:
        print(row)

['', 'MINISTRY OF LOCAL GOVERNMENT AND RURAL DEVELOPMENT - MPONGWE', None, None, None, None, None, None, None, '']
[None, 'TOWN COUNCIL', None, None, None, None, None, None, None, None]
['', None, '', None, None, '', '', '', '', None]
['COMMUNITY PROJECTS', None, None, None, None, None, None, None, None, None]
['MPONGWE CONSTITUENCY 2025 APPROVED AND NOT APPROVED CDF PROJECTS', None, None, None, None, None, None, None, None, None]
['No.', None, 'Project Name/\nDescription', None, None, 'Sector', 'Ward', 'Approved', 'Not Approved', None]
['1', None, '', 'Construction of a', '', 'Education', 'Kasamba', '', 'Inadequate Funding', None]
[None, None, None, '1X4 CRB at', None, None, None, None, None, None]
[None, None, None, 'Kasamba', None, None, None, None, None, None]
[None, None, None, 'Secondary', None, None, None, None, None, None]

## Full PDF Text Extraction

In [64]:
all_text = []

with pdfplumber.open(pdf_path) as pdf:
    for page_number, page in enumerate(pdf.pages, start=1):
        text = page.extract_text()

        if text:
            all_text.append(text)

full_text = "\n".join(all_text)

print(full_text[:5000])

MINISTRY OF LOCAL GOVERNMENT AND RURAL DEVELOPMENT - MPONGWE
TOWN COUNCIL
COMMUNITY PROJECTS
MPONGWE CONSTITUENCY 2025 APPROVED AND NOT APPROVED CDF PROJECTS
Project Name/ Sector Ward Approved Not Approved
No. Description
1 Construction of a Education Kasamba Inadequate Funding
1X4 CRB at
Kasamba
Secondary
School with
laborotory;purch
ase of 200
desks,one staff
house and solar
powered
borehole
2 Construction of 1 Health Kasamba It was not the first
staff house and priority
completion of 1
staff house at
Kasamba Rural
Health Center
3 Construction of 1 Education Kasamba It was not the first
staff house; priority
purchase of 80
desks and solar
powered
borehole at
Mikumbi
primary School
4 Construction of a Education Kasamba It was not the first
Community priority
School at Fikola
area.
5 Construction of 1 Education Kasamba It was not the first
staff house and priority
purchase of 80
desks at
Minkoyo
Primary School
6 Construction of a Health Kasamba It was not the first
health post at priority
Bwandaila in
Milonfi
7 Construction of Education/Health Kasamba It was not the first
1x3 CRB; priority
cnstruction of
health post and
purchase of solar
powered
borehole in
Milonfi
8 Construction of Health Kasamba Approved
staff house,
ablution block,
water reticulation
system and
medical tools at
Mikumbi health
post
9 Construction of Education kanyenda It was not the first
1x3 CRB at priority
Michinka
Community
School
10 Completion of Education kanyenda Approved
1x3 CRB and 1
staff house at
Buyantanshi
School
11 Construction of 1 Education kanyenda It was not the first
staff house at priority
Nkulumashiba
School
12 Construction of Education kanyenda It was not the first
1x3 CRB at priority
Chibuli Primary
School
13 Completion of 1 Health Kanyenda Approved
staff house at
Kanyenda Clinic
14 Construction of Education Ntanda It was not the first
1x3 CRB and 2 priority
staff houses at
Makombo in
Muchindushi
15 Construction of Education Ntanda it was not on the first
1x3 CRB at priority
Swaya
Community
School
16 Construction of Education Ntanda Approved
1x3 CRB and 2
staff houses in
Twikatane
17 Construction of Education Ntanda it was not on the first
1x3 CRB and 2 priority
staff houses in
Chibangu
18 Construction of 2 Education Ntanda it was not on the first
staff houses at priority
Lukanga north B
school in
Lukanga North
19 Construction of 3 Education Ntanda it was not on the first
staff houses and priority
3 toilets at
Ntanda primary
School
20 Construction of Education Kashiba it was not on the first
1x3 CRB at Ikula priority
Community
School
21 Construction of Education Kashiba it was not on the first
1x3 CRB at priority
Water Affairs
Community
School
22 Construction of 1 Education Kashiba it was not on the first
staff house at priority
Chinampanga
Community
School
23 Construction of 1 Health Kashiba it was not on the first
staff house at priority
Mfulabunga
Clinic
24 Construction of Education Luswishi it was not on the first
1x3 CRB and 2 priority
staff houses at
Luswishi
Primary School
25 Construction of Luswishi it was not on the first
Luswishi Market priority
in the ward
26 Construction of Education Luswishi it was not on the first
1x3 CRB and 1 priority
staff house at
Mayewe
Community
School
27 Construction of Education Luswishi it was not on the first
1x3 CRB and 1 priority
staff house at
Kalabi
Community
School
28 Construction of Health Luswishi it was not on the first
maternity wing at priority
Luswishi Health
post
29 Construction of Education Mpongwe it was not on the first
Mpongwe Central priority
Central
Secondary
School
30 Construction of information Mpongwe It was not a priority
M.B.A Central
Community
Radio Station
studio with
furniture,eqiupm
ent and other
items needed
31 Construction of Local Mpongwe Approved
Parliamentary government Central
Constituency
Office
32 Construction of Health Mpongwe It was not on the first
Mothers waiting Central priority and the hospital
shelter at was funded in the
Mpongwe previous year with
Mission Hospital medical equipment such
as incubator, theatre
operating,
phototheraphy,
anaesthetic machine etc
33 Procurement of Mpongwe Instead
motor bikes and Central Bicycles
bicyles for were
WDCs approved
34 Procurement a Transport Mpongwe Approved
roller compactor Central
35 Construction of Education Mpongwe Approved
Ablution blocks Central
and water
reticulation at
Buni Primary
School
36 Construction of a Security Mpongwe There was already a
modern police Central morden police station
station under construction even
though works had
stalled. The project is
under the Ministry of
Infrastructure
37 Renovation of Health Mpongwe There were no
Old District Central documentation for the
Administration transfer of property from
Office into Rural the Provincial
Urban Central Adminisration
Clinic
38 Purchase of X- Health Mpongwe Inadequate Funding
Ray and Scanner Central
at Mpongwe
Mission Hospital
39 Purchase of solar Mpongwe it was not on the first
panel as power Central priority
backup for
N

In [65]:
import re

project_numbers = re.findall(r"(?m)^\d+\s+", full_text)

print("Possible project records found:", len(project_numbers))

Possible project records found: 86

## Project Record Segmentation

In [66]:
records = re.split(r"(?m)(?=^\d+\s+)", full_text)

records = [
    record.strip()
    for record in records
    if re.match(r"^\d+\s+", record.strip())
]

print("Project blocks found:", len(records))

Project blocks found: 86

In [67]:
for i, record in enumerate(records[:3], start=1):
    print(f"\n--- RECORD {i} ---")
    print(record)

--- RECORD 1 ---
1 Construction of a Education Kasamba Inadequate Funding
1X4 CRB at
Kasamba
Secondary
School with
laborotory;purch
ase of 200
desks,one staff
house and solar
powered
borehole

--- RECORD 2 ---
2 Construction of 1 Health Kasamba It was not the first
staff house and priority
completion of 1
staff house at
Kasamba Rural
Health Center

--- RECORD 3 ---
3 Construction of 1 Education Kasamba It was not the first
staff house; priority
purchase of 80
desks and solar
powered
borehole at
Mikumbi
primary School

## Structured Record Parsing

In [68]:
known_sectors = [
    "Education",
    "Health",
    "Roads",
    "Water",
    "Agriculture",
    "Community Development",
    "Public Infrastructure"
]

known_wards = [
    "Kasamba"
]

In [69]:
parsed_records = []

for record in records:
    lines = [line.strip() for line in record.split("\n") if line.strip()]

    first_line = lines[0]

    match = re.match(r"^(\d+)\s+(.*)", first_line)

    if not match:
        continue

    project_no = match.group(1)
    first_line_rest = match.group(2)

    full_record = " ".join(lines)

    sector = None
    ward = None

    for s in known_sectors:
        if s.lower() in full_record.lower():
            sector = s
            break

    for w in known_wards:
        if w.lower() in full_record.lower():
            ward = w
            break

    parsed_records.append({
        "project_no": project_no,
        "raw_record": full_record,
        "sector": sector,
        "ward": ward
    })

parsed_df = pd.DataFrame(parsed_records)

parsed_df.head()

,project_no,raw_record,sector,ward
0,1,1 Construction of a Education Kasamba Inadequa...,Education,Kasamba
1,2,2 Construction of 1 Health Kasamba It was not ...,Health,Kasamba
2,3,3 Construction of 1 Education Kasamba It was n...,Education,Kasamba
3,4,4 Construction of a Education Kasamba It was n...,Education,Kasamba
4,5,5 Construction of 1 Education Kasamba It was n...,Education,Kasamba

In [70]:
parsed_df.shape

(86, 4)

In [71]:
parsed_df[["project_no", "sector", "ward"]].head(10)

  project_no     sector     ward
0          1  Education  Kasamba
1          2     Health  Kasamba
2          3  Education  Kasamba
3          4  Education  Kasamba
4          5  Education  Kasamba
5          6     Health  Kasamba
6          7  Education  Kasamba
7          8     Health  Kasamba
8          9  Education      NaN
9         10  Education      NaN

In [72]:
for i, record in enumerate(records[:20], start=1):
    print(f"\n--- RECORD {i} ---")
    print(record)

--- RECORD 1 ---
1 Construction of a Education Kasamba Inadequate Funding
1X4 CRB at
Kasamba
Secondary
School with
laborotory;purch
ase of 200
desks,one staff
house and solar
powered
borehole

--- RECORD 2 ---
2 Construction of 1 Health Kasamba It was not the first
staff house and priority
completion of 1
staff house at
Kasamba Rural
Health Center

--- RECORD 3 ---
3 Construction of 1 Education Kasamba It was not the first
staff house; priority
purchase of 80
desks and solar
powered
borehole at
Mikumbi
primary School

--- RECORD 4 ---
4 Construction of a Education Kasamba It was not the first
Community priority
School at Fikola
area.

--- RECORD 5 ---
5 Construction of 1 Education Kasamba It was not the first
staff house and priority
purchase of 80
desks at
Minkoyo
Primary School

--- RECORD 6 ---
6 Construction of a Health Kasamba It was not the first
health post at priority
Bwandaila in
Milonfi

--- RECORD 7 ---
7 Construction of Education/Health Kasamba It was not the first
1x3 CRB; priority
cnstruction of
health post and
purchase of solar
powered
borehole in
Milonfi

--- RECORD 8 ---
8 Construction of Health Kasamba Approved
staff house,
ablution block,
water reticulation
system and
medical tools at
Mikumbi health
post

--- RECORD 9 ---
9 Construction of Education kanyenda It was not the first
1x3 CRB at priority
Michinka
Community
School

--- RECORD 10 ---
10 Completion of Education kanyenda Approved
1x3 CRB and 1
staff house at
Buyantanshi
School

--- RECORD 11 ---
11 Construction of 1 Education kanyenda It was not the first
staff house at priority
Nkulumashiba
School

--- RECORD 12 ---
12 Construction of Education kanyenda It was not the first
1x3 CRB at priority
Chibuli Primary
School

--- RECORD 13 ---
13 Completion of 1 Health Kanyenda Approved
staff house at
Kanyenda Clinic

--- RECORD 14 ---
14 Construction of Education Ntanda It was not the first
1x3 CRB and 2 priority
staff houses at
Makombo in
Muchindushi

--- RECORD 15 ---
15 Construction of Education Ntanda it was not on the first
1x3 CRB at priority
Swaya
Community
School

--- RECORD 16 ---
16 Construction of Education Ntanda Approved
1x3 CRB and 2
staff houses in
Twikatane

--- RECORD 17 ---
17 Construction of Education Ntanda it was not on the first
1x3 CRB and 2 priority
staff houses in
Chibangu

--- RECORD 18 ---
18 Construction of 2 Education Ntanda it was not on the first
staff houses at priority
Lukanga north B
school in
Lukanga North

--- RECORD 19 ---
19 Construction of 3 Education Ntanda it was not on the first
staff houses and priority

--- RECORD 20 ---
3 toilets at
Ntanda primary
School

In [73]:
clean_records = []

expected_number = 1

for record in records:
    match = re.match(r"^(\d+)\s+", record.strip())

    if not match:
        continue

    number = int(match.group(1))

    if number == expected_number:
        clean_records.append(record.strip())
        expected_number += 1
    else:
        # This is probably a continuation line such as
        # "3 toilets at..."
        if clean_records:
            clean_records[-1] += "\n" + record.strip()

print("Clean project records:", len(clean_records))

Clean project records: 84

In [74]:
known_wards = [
    "Kasamba",
    "Kanyenda",
    "Ntanda"
]

In [75]:
print("Clean project records:", len(clean_records))

Clean project records: 84

In [76]:
project_nums = []

for record in clean_records:
    match = re.match(r"^(\d+)\s+", record.strip())
    if match:
        project_nums.append(int(match.group(1)))

print(project_nums)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84]

In [77]:
missing_numbers = [
    n for n in range(1, max(project_nums) + 1)
    if n not in project_nums
]

print("Missing project numbers:", missing_numbers)

Missing project numbers: []

In [78]:
from collections import Counter

counts = Counter(project_nums)

duplicates = [
    num for num, count in counts.items()
    if count > 1
]

print("Duplicate project numbers:", duplicates)

Duplicate project numbers: []

In [79]:
print("First project:", project_nums[0])
print("Last project:", project_nums[-1])
print("Total projects:", len(project_nums))

First project: 1
Last project: 84
Total projects: 84

In [80]:
parsed_records = []

for record in clean_records:
    lines = [line.strip() for line in record.split("\n") if line.strip()]

    first_line = lines[0]

    match = re.match(r"^(\d+)\s+(.*)", first_line)

    if not match:
        continue

    project_no = match.group(1)
    full_record = " ".join(lines)

    sector = None
    ward = None

    for s in known_sectors:
        if s.lower() in full_record.lower():
            sector = s
            break

    for w in known_wards:
        if w.lower() in full_record.lower():
            ward = w
            break

    parsed_records.append({
        "project_no": project_no,
        "raw_record": full_record,
        "sector": sector,
        "ward": ward
    })

parsed_df = pd.DataFrame(parsed_records)

In [81]:
parsed_df.shape

(84, 4)

In [82]:
parsed_df[["project_no", "sector", "ward"]].head(20)

   project_no     sector      ward
0           1  Education   Kasamba
1           2     Health   Kasamba
2           3  Education   Kasamba
3           4  Education   Kasamba
4           5  Education   Kasamba
5           6     Health   Kasamba
6           7  Education   Kasamba
7           8     Health   Kasamba
8           9  Education  Kanyenda
9          10  Education  Kanyenda
10         11  Education  Kanyenda
11         12  Education  Kanyenda
12         13     Health  Kanyenda
13         14  Education    Ntanda
14         15  Education    Ntanda
15         16  Education    Ntanda
16         17  Education    Ntanda
17         18  Education    Ntanda
18         19  Education    Ntanda
19         20  Education       NaN

In [83]:
parsed_df.shape

(84, 4)

##identifying the remaining ward n ames automatically.

In [85]:
missing_ward_records = parsed_df[parsed_df["ward"].isna()]

print("Records with missing ward:", len(missing_ward_records))

Records with missing ward: 64

In [86]:
for _, row in missing_ward_records.iterrows():
    print(f"\n--- PROJECT {row['project_no']} ---")
    print(row["raw_record"])

--- PROJECT 20 ---
20 Construction of Education Kashiba it was not on the first 1x3 CRB at Ikula priority Community School

--- PROJECT 21 ---
21 Construction of Education Kashiba it was not on the first 1x3 CRB at priority Water Affairs Community School

--- PROJECT 22 ---
22 Construction of 1 Education Kashiba it was not on the first staff house at priority Chinampanga Community School

--- PROJECT 23 ---
23 Construction of 1 Health Kashiba it was not on the first staff house at priority Mfulabunga Clinic

--- PROJECT 24 ---
24 Construction of Education Luswishi it was not on the first 1x3 CRB and 2 priority staff houses at Luswishi Primary School

--- PROJECT 25 ---
25 Construction of Luswishi it was not on the first Luswishi Market priority in the ward

--- PROJECT 26 ---
26 Construction of Education Luswishi it was not on the first 1x3 CRB and 1 priority staff house at Mayewe Community School

--- PROJECT 27 ---
27 Construction of Education Luswishi it was not on the first 1x3 CRB and 1 priority staff house at Kalabi Community School

--- PROJECT 28 ---
28 Construction of Health Luswishi it was not on the first maternity wing at priority Luswishi Health post

--- PROJECT 29 ---
29 Construction of Education Mpongwe it was not on the first Mpongwe Central priority Central Secondary School

--- PROJECT 30 ---
30 Construction of information Mpongwe It was not a priority M.B.A Central Community Radio Station studio with furniture,eqiupm ent and other items needed

--- PROJECT 31 ---
31 Construction of Local Mpongwe Approved Parliamentary government Central Constituency Office

--- PROJECT 32 ---
32 Construction of Health Mpongwe It was not on the first Mothers waiting Central priority and the hospital shelter at was funded in the Mpongwe previous year with Mission Hospital medical equipment such as incubator, theatre operating, phototheraphy, anaesthetic machine etc

--- PROJECT 33 ---
33 Procurement of Mpongwe Instead motor bikes and Central Bicycles bicyles for were WDCs approved

--- PROJECT 34 ---
34 Procurement a Transport Mpongwe Approved roller compactor Central

--- PROJECT 35 ---
35 Construction of Education Mpongwe Approved Ablution blocks Central and water reticulation at Buni Primary School

--- PROJECT 36 ---
36 Construction of a Security Mpongwe There was already a modern police Central morden police station station under construction even though works had stalled. The project is under the Ministry of Infrastructure

--- PROJECT 37 ---
37 Renovation of Health Mpongwe There were no Old District Central documentation for the Administration transfer of property from Office into Rural the Provincial Urban Central Adminisration Clinic

--- PROJECT 38 ---
38 Purchase of X- Health Mpongwe Inadequate Funding Ray and Scanner Central at Mpongwe Mission Hospital

--- PROJECT 39 ---
39 Purchase of solar Mpongwe it was not on the first panel as power Central priority backup for National Assembly Mpongwe Constituency

--- PROJECT 40 ---
40 Construction of Health Kasonga Inadequate Funding Mitumba Hill Health Post

--- PROJECT 41 ---
41 Construction of Education Kasonga Inadequate Funding 1x3 CRB at Mangonwa Community School

--- PROJECT 42 ---
42 Construction of Education Kasonga Inadequate Funding 1x3 CRB at Chunga Community School

--- PROJECT 43 ---
43 Construction of Agriculture Kasonga Inadequate Funding Agricultural staff house at Mushiwe

--- PROJECT 44 ---
44 Construction of Education Kasonga Inadequate Funding 1x3 CRB at Kasonkomona twebo Primary School

--- PROJECT 45 ---
45 Construction of Education Ipumbu Inadequate Funding 1x3 CRB at Nkulushu Primary School

--- PROJECT 46 ---
46 Construction of a Economic Ipumbu Approved; market shelter Constructi and ablution on of block at Ipumbu market Market shelter

--- PROJECT 47 ---
47 Construction of 1 Health Ipumbu Inadequate Funding staff house,ablution block and eqiupment for mothers shelter at Ipumbu Clinic.

--- PROJECT 48 ---
48 Upgrade of Health Ibenga Inadequate Funding St.theresa's Mission Hospital mortuary

--- PROJECT 49 ---
49 Istallation of Infrastructure Ibenga Inadequate Funding street lights at Ibenga trading area a stretch of 2kilometers

--- PROJECT 50 ---
50 Construction of a Transport Ibenga Inadequate Funding bridge at Ibenga river in Butikili

--- PROJECT 51 ---
51 Construction of a Health Ibenga Approved staff at Mulilantambo clinic

--- PROJECT 52 ---
52 Construction of Education Ibenga Inadequate Funding ablution block at St.theresa's Secondary school

--- PROJECT 53 ---
53 Construction of 2 Education Ibenga Inadequate Funding staff houses and ablution block at Mipini School

--- PROJECT 54 ---
54 Construction of Education Nampamba Inadequate Funding 1x3 CRB in Chawama zone

--- PROJECT 55 ---
55 Upgrade of Water and Nampamba Inadequate Funding Mpuku borehole Sanitation in Mwanga zone

--- PROJECT 56 ---
56 Construction of Transport Nampamba Inadequate Funding Muchindushi bridge in Chowa zone

--- PROJECT 57 ---
57 Construction of a Health Nampamba Approved staff house, ablution block and water reticulation at chowa health post

--- PROJECT 58 ---
58 Completion of Health Nampamba Inadequate Funding John Chawa clinic in Chawama zone

--- PROJECT 59 ---
59 Construction of Education Chisapa Inadequate Funding 1x3 CRB and 2 staff houses at Malembeka Primary School

--- PROJECT 60 ---
60 Drilling of solar Education Chisapa Inadequate Funding powered borehole at Kantolo Primary School

--- PROJECT 61 ---
61 Grading of road Road/ Transport Chisapa Inadequate Funding connecting Kantolo to Chisapa

--- PROJECT 62 ---
62 Construction of a Communication Chisapa Not amongst the network tower in recommended projects the ward in the CDF Guidelines

--- PROJECT 63 ---
63 Construction of a Education Chisapa Inadequate Funding pre-school in Chitina area.

--- PROJECT 64 ---
64 Grading of road Musofu Inadequate Funding from Kapitolo to Mushipashi

--- PROJECT 65 ---
65 Drilling of solar Water and Musofu Inadequate Funding powered Sanitation boreholes at Musofu market,Kabampa nga market,chitube community school

--- PROJECT 66 ---
66 Upgradin of Education Musofu Inadequate Funding Mwinuna primary,Mushipa shi primary and Miyanda Community school

--- PROJECT 67 ---
67 Upgrade of Health Musofu Inadequate Funding Mwinuna and Mushipashi Health posts into Modern clinics.

--- PROJECT 69 ---
69 Construction of 3 Education Mikata Inadequate Funding dormitories for girls at Chintifu Secondary School

--- PROJECT 70 ---
70 Construction of Education Mikata Inadequate Funding 1x3 CRB at Nawanda Community School

--- PROJECT 71 ---
71 Construction of Education Mikata Inadequate Funding 1x3 CRB at Njili Community School

--- PROJECT 72 ---
72 Construction of Education Mikata Inadequate Funding 1x3 CRB at Mipini Community School

--- PROJECT 73 ---
73 Upgrading of Health Mikata Inadequate Funding Mikata Rural Health Center to mini hospital

--- PROJECT 74 ---
74 Construction of a Security Munkumpu Approved Police post in Munkumpu Central

--- PROJECT 75 ---
75 Construction of 2 Education Munkumpu Inadequate Funding staff houses in Mulele

--- PROJECT 76 ---
76 Construction of a Health & Road Munkumpu Inadequate Funding health post and grading of feeder road in Chitabale

--- PROJECT 77 ---
77 Construction of a Education Munkumpu Inadequate Funding Community School in Chilelwe

--- PROJECT 78 ---
78 Drilling of Water and Munkumpu Inadequate Funding boreholes for Sanitation each zone in the ward

--- PROJECT 79 ---
79 Construction of Education Kalweo Inadequate Funding 1x3 CRB,1 staff house and a borehole in Shibulwa

--- PROJECT 80 ---
80 Construction of Education Kalweo Inadequate Funding 1x2 CRB,1 staff house and a borehole in Busakalala

--- PROJECT 81 ---
81 Construction of Education Kalweo Inadequate Funding 1x3 CRB,1 staff house and a borehole in Chibuli

--- PROJECT 82 ---
82 Construction of Education Kalweo Inadequate Funding 1x3 CRB and a staff house in luamabwe

--- PROJECT 83 ---
83 Construction of Education Kalweo Inadequate Funding 1x3 CRB in Muyambe

--- PROJECT 84 ---
84 Purchase and Education All Wards Approved distribution of 4000 Desks

In [87]:
known_wards = [
    "Kasamba",
    "Kanyenda",
    "Ntanda",
    "Kashiba",
    "Luswishi",
    "Mpongwe Central",
    "Kasonga",
    "Ipumbu",
    "Ibenga",
    "Nampamba",
    "Chisapa",
    "Musofu",
    "Mikata",
    "Munkumpu",
    "Kalweo",
    "All Wards"
]