# CSC4792 Data Mining and Warehousing
## Group 26 — Mpongwe Town Council Dataset
This notebook documents the extraction, cleaning, preprocessing, validation and export of data collected from official Mpongwe Town Council sources.

In [19]:
import pandas as pd

In [20]:
file_path = "../data/processed/db-unza26-csc4792-mpongwe_cdf_projects.csv"

df = pd.read_csv(file_path, sep="|")

df.head()

,project_id,sector,ward,project_name,approval_status,reason_not_approved,year,source_document,source_url
0,CDF2025-001,Education,Kasamba,Construction of a 1X4 CRB at Kasamba Secondary...,Not Approved,Inadequate funding,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,NaN
1,CDF2025-002,Health,Kasamba,Construction of 1 staff house and completion o...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,NaN
2,CDF2025-003,Education,Kasamba,Construction of 1 staff house; purchase of 80 ...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,NaN
3,CDF2025-004,Education,Kasamba,Construction of a Community School at Fikola a...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,NaN
4,CDF2025-005,Education,Kasamba,Construction of 1 staff house and purchase of ...,Not Approved,It was not the first priority,2025,Mpongwe 2025 Approved and Unapproved CDF Commu...,NaN

In [21]:
df.shape

(5, 9)

## Initial Data Inspection

The dataset is inspected to verify its structure, data types, missing values and possible duplicate records before further processing.

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   project_id           5 non-null      str
 1   sector               5 non-null      str
 2   ward                 5 non-null      str
 3   project_name         5 non-null      str
 4   approval_status      5 non-null      str
 5   reason_not_approved  5 non-null      str
 6   year                 5 non-null      int64
 7   source_document      5 non-null      str
 8   source_url           0 non-null      float64
dtypes: float64(1), int64(1), str(7)
memory usage: 492.0 bytes

In [23]:
df.isnull().sum()

project_id             0
sector                 0
ward                   0
project_name           0
approval_status        0
reason_not_approved    0
year                   0
source_document        0
source_url             5
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

## Source URL Completion

In [26]:
source_url = "http://www.mpongwecouncil.gov.zm/wp-content/uploads/2025/11/APPROVED-AND-UNAPPROVED-COMMUNITY-PROJECTS-2025.pdf"
df["source_url"] = df["source_url"].fillna(source_url)

In [29]:
df.isnull().sum()

project_id             0
sector                 0
ward                   0
project_name           0
approval_status        0
reason_not_approved    0
year                   0
source_document        0
source_url             0
dtype: int64

## Text Cleaning and Standardisation

In [31]:
text_columns = [
    "sector",
    "ward",
    "project_name",
    "approval_status",
    "reason_not_approved",
    "source_document"
]
for col in text_columns:
    df[col] = df[col].astype(str).str.strip()

In [32]:
df["sector"] = df["sector"].str.title()
df["ward"] = df["ward"].str.title()
df["approval_status"] = df["approval_status"].str.title()

In [33]:
df["project_name"] = (
    df["project_name"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

df["reason_not_approved"] = (
    df["reason_not_approved"]
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
)

In [34]:
df[
    [
        "project_id",
        "sector",
        "ward",
        "project_name",
        "approval_status",
        "reason_not_approved"
    ]
]

,project_id,sector,ward,project_name,approval_status,reason_not_approved
0,CDF2025-001,Education,Kasamba,Construction of a 1X4 CRB at Kasamba Secondary...,Not Approved,Inadequate funding
1,CDF2025-002,Health,Kasamba,Construction of 1 staff house and completion o...,Not Approved,It was not the first priority
2,CDF2025-003,Education,Kasamba,Construction of 1 staff house; purchase of 80 ...,Not Approved,It was not the first priority
3,CDF2025-004,Education,Kasamba,Construction of a Community School at Fikola a...,Not Approved,It was not the first priority
4,CDF2025-005,Education,Kasamba,Construction of 1 staff house and purchase of ...,Not Approved,It was not the first priority